version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: notte-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: notte
      MYSQL_USER: notte
      MYSQL_PASSWORD: notte
      MYSQL_ROOT_PASSWORD: notte
    volumes:
      - mysql:/var/lib/mysql

  user:
    build:
      context: docker/node-18
      args:
        UID: $HOST_UID
        GID: $HOST_GID
    container_name: notte-user
    command: sh -c "bin/migrate && npm run start:dev"
    env_file:
      - ./services/user/dev.env
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    volumes:
      - ./services/user:/home/node/app
    depends_on:
      - mysql

  auth:
    build:
      context: docker/deno-1.36
      args:
        UID: $HOST_UID
        GID: $HOST_GID
    container_name: notte-auth
    ports:
      - "3001:3001"
    env_file:
      - ./services/auth/dev.env
    volumes:
      - ./services/auth:/home/deno/app
    command: bash
    tty: true
    stdin_open: true

volumes:
  mysql:
