version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mysql:
    image: mysql:8
    container_name: notte-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: notte
      MYSQL_USER: notte
      MYSQL_PASSWORD: notte
      MYSQL_ROOT_PASSWORD: notte
      MYSQL_LOG_BIN: ON
      MYSQL_BINLOG_FORMAT: ROW
      MYSQL_EXPIRE_LOGS_DAYS: "7"
      VIRTUAL_HOST: notte-mysql.localtest.me
    volumes:
      - mysql:/var/lib/mysql
    depends_on:
      - nginx-proxy

  user:
    build:
      context: docker/node-18
      args:
        UID: $HOST_UID
        GID: $HOST_GID
    container_name: notte-user
    command: sh -c "bin/migrate && npm run start:dev"
    env_file:
      - ./services/user/dev.env
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: notte-user.localtest.me
    working_dir: /home/node/app
    volumes:
      - ./services/user:/home/node/app
    depends_on:
      - nginx-proxy
      - mysql

  auth:
    build:
      context: docker/python-3.10
      args:
        UID: $HOST_UID
        GID: $HOST_GID
    container_name: notte-auth
    command: bash
    tty: true
    stdin_open: true
    env_file:
      - ./services/auth/dev.env
    environment:
      VIRTUAL_HOST: notte-auth.localtest.me
    working_dir: /home/notte/app
    volumes:
      - ./services/auth:/home/notte/app
    depends_on:
      - nginx-proxy

volumes:
  mysql:
