#!/bin/bash

MYSQL_USER="root"
MYSQL_PASSWORD="notte"
DATABASE_NAME="$1"

docker compose exec mysql sh -c "
  if mysql -u '$MYSQL_USER' -p'$MYSQL_PASSWORD' -e \"USE $DATABASE_NAME;\" &>/dev/null; then
    echo \"Database '$DATABASE_NAME' already exists. Skipping creation.\"
  else
    mysql -u '$MYSQL_USER' -p'$MYSQL_PASSWORD' -e \"CREATE DATABASE $DATABASE_NAME;GRANT ALL PRIVILEGES ON *.* TO 'notte'@'%';\"
    echo \"Database '$DATABASE_NAME' created successfully.\"
  fi
"
