#!/bin/bash

MYSQL_USER="root"
MYSQL_PASSWORD="notte"
DATABASE_NAME="$1"

docker compose exec mysql sh -c "
  db_exists=\$(mysql -u '$MYSQL_USER' -p'$MYSQL_PASSWORD' -e \"SHOW DATABASES LIKE '$DATABASE_NAME';\" | grep -o '$DATABASE_NAME')

  if [ \"\$db_exists\" = \"$DATABASE_NAME\" ]; then
    echo \"Database '$DATABASE_NAME' already exists. Skipping creation.\"
  else
    mysql -u '$MYSQL_USER' -p'$MYSQL_PASSWORD' -e \"CREATE DATABASE $DATABASE_NAME;GRANT ALL PRIVILEGES ON $DATABASE_NAME.* TO 'notte'@'%';\"
    echo \"Database '$DATABASE_NAME' created successfully.\"
  fi
"
